import {
    InitializeVPDL as InitializeIoTVPDL
} from "./src/app/ide/domains/IoT/vpdl/iot-domain";
import {
    InitializeVPDL as InitializeSimpleDomainVPDL
} from "./src/app/ide/domains/SimpleTasks/vpdl/simple-domain";

//TODO: autogenerated using the python scripts
// manually added now

export function InitializeVPDLs() {
    InitializeIoTVPDL();
    InitializeSimpleDomainVPDL();
}
