import {
    InitializeVPDL as InitializeIoTVPDL
} from "./IoT/vpdl/iot-domain";
import {
    InitializeVPDL as InitializeSimpleDomainVPDL
} from "./SimpleTasks/vpdl/simple-domain";

//TODO: autogenerated using the python scripts
// manually added now

export function InitializeVPDLs() {
    InitializeIoTVPDL();
    InitializeSimpleDomainVPDL();
}
