import { InitializeVPDL as InitializeIoTVPDL } from "./IoT/vpdl/iot-domain";

//TODO: autogenerated using the python scripts
// manually added now

export function InitializeVPDLs() {
    InitializeIoTVPDL();
}
