import {
    InitializeVPDL as InitializeIoTVPDL
} from "./src/app/ide/domains/IoT/vpdl/domain";
import {
    InitializeVPDL as InitializeSimpleDomainVPDL
} from "./src/app/ide/domains/SimpleTasks/vpdl/domain";

//TODO: autogenerated using the python scripts
// manually added now

export function InitializeVPDLs() {
    InitializeIoTVPDL();
    InitializeSimpleDomainVPDL();
}
