
/*
  id          : "string" // will be autogenerated if omitted
  text        : "string" // node text
  icon        : "string" // string for custom
  state       : {
    opened    : boolean  // is the node open
    disabled  : boolean  // is the node disabled
    selected  : boolean  // is the node selected
  },
  li_attr     : {}  // attributes for the generated LI node
  a_attr      : {}  // attributes for the generated A node

  // used parent or children for the connections...
  parent: "string" // required
  children    : []  // array of strings or objects
*/

function customMenu(node) {

}

$(function () {
    $('#jstree_div').jstree({
        "plugins" : [
            "colorv",
            // "checkbox",
            "wholerow",
            "contextmenu",
            "unique",
            "types"
        ],
        // 'contextmenu': {
        //     'items': customMenu
        // },
        'types': {
            'smart_object': {},
            'other': {}
        },
        'core' : {
            'check_callback': true,
            'data' : [
                {
                    'id': 'node_0',
                    'parent': '#',
                    'text': 'Simple root node',
                    'color': '#0066ff',
                    'icon': './images/person.png',
                    'extra': {
                        'color': '',
                        'shared': 'colab or local or shared',
                        'so_state': 'online or offline or ',
                        'bubble': {
                            'color': 'html',
                            'pos': 'up-left or up-right or down-left or down-right'
                        },
                        'previleges' : [
                            {
                                "type": "corona or edit",
                                "pos": "top or bottom"
                            }
                            //, ...

                        ]
                    }
                },
                {
                    'id': 'node_1',
                    'parent': '#',
                    'type': 'other',
                    'text' : 'Root node 2',
                    'color': '#6666ff'
                    // ,
                    // 'children' : [
                    //     {
                    //         'id': 'node_2',
                    //         'text' : 'Child 1',
                    //         'color': 'red',
                    //         'state' : {
                    //             'opened' : true,
                    //             'selected' : true
                    //         },
                    //         'icon': 'glyphicon glyphicon-pencil'
                    //     },
                    //     {
                    //         'id': 'node_3',
                    //         'text': 'Child 2'
                    //     }
                    // ]
                },
                {
                        'id': 'node_2',
                        'parent': 'node_1',
                    'type': 'smart_object',
                        'text' : 'Child 1',
                        'color': 'red',
                        'state' : {
                            'opened' : true,
                            'selected' : true
                        },
                        'icon': 'glyphicon glyphicon-pencil'
                    },
                    {
                        'id': 'node_3',
                        'type': 'smart_object',
                        'parent': 'node_1',
                        'text': 'Child 2'
                    }

            ]
        }
    });

    $('#change_color').on('click', function () {
        changeNodeItem('jstree_div', 'node_1', 'color', 'black');
    });
    $('#change_text').on('click', function () {
        changeNodeItem('jstree_div', 'node_1', 'text', 'updated text here...');
    });
    $('#add_node').on('click', function () {
        createNodeItem('jstree_div', 'node_1', 'text', 'updated text here...');
    });
});

function changeNodeItem(treeId, nodeId, item, value) {
    let jstree = $.jstree.reference("#"+treeId);
    jstree.get_node(nodeId)[item] = value;
    jstree.redraw_node(nodeId);
}

function createNodeItem(treeId, node) {}